services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: music
      POSTGRES_PASSWORD: music
      POSTGRES_DB: musicdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music -d musicdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://music:music@db:5432/musicdb
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  pgdata: